<a href="https://colab.research.google.com/github/Vixuz144/Admin-Prod/blob/main/Copia_de_Copia_de_Ex1_Admin_Prod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from statistics import mode

## Transporte

In [ ]:
def MEN(cost, dem, prod):
  d = list(dem)
  p = list(prod)
  s = sum(p)
  t = np.zeros_like(cost)

  i, j = 0, 0
  while np.sum(t) < s:
    if min(p[i], d[j]) == p[i]:
      t[i,j] = p[i]
      d[j] -= p[i]
      p[i] = 0
      i+=1
    else:
      t[i,j] = d[j]
      p[i] -= d[j]
      d[j] = 0
      j+=1
  c = np.sum(cost*t)
  return t, c

In [ ]:
def MCM(cost, dem, prod):
  C = np.array(tuple(cost))
  d = list(dem)
  p = list(prod)

  s = sum(p)
  t = np.zeros_like(cost)

  while np.sum(t) < s:
    i, j = np.unravel_index(np.argmin(C),np.shape(C))
    if min(p[i], d[j]) == p[i]:
      t[i,j] = p[i]
      d[j] -= p[i]
      p[i] = 0
      C[i,j] = np.inf
    else:
      t[i,j] = d[j]
      p[i] -= d[j]
      d[j] = 0
      C[i,j] = np.inf
  c = np.sum(cost*t)
  return t, c

In [ ]:
def MAV(cost, dem, prod):
  C = np.array(tuple(cost))
  d = list(dem)
  p = list(prod)

  s = sum(p)
  t = np.zeros_like(cost)

  m = len(prod)
  n = len(dem)

  while np.sum(t) < s:
    # print(t)
    # print(C)
    dif0 = []
    for k in range(m):
      di = []
      l = list(C[k, :])
      di.append(l.pop(np.nanargmin(l)))
      di.append(l.pop(np.nanargmin(l)))
      if np.any(np.isinf(di)):
        dif0.append(0)
      else:
        dif0.append(abs(di[0] - di[1]))

    dif1 = []
    for k in range(n):
      di = []
      l = list(C[:, k])
      di.append(l.pop(np.nanargmin(l)))
      di.append(l.pop(np.nanargmin(l)))
      if np.any(np.isinf(di)):
        dif1.append(0)
      else:
        dif1.append(abs(di[0] - di[1]))
    # print(dif0, dif1)
    mm = max(max(dif0), max(dif1))
    if mm in dif0:
      i = dif0.index(mm)
      j = np.nanargmin(list(C[i,:]))
    else:
      j = dif1.index(mm)
      i = np.nanargmin(list(C[:,j]))
    # print(i,j)
    # print(p,d)
    if min(p[i], d[j]) == p[i]:
      t[i,j] = p[i]
      d[j] -= p[i]
      p[i] = 0
      C[i,:] = np.inf
    else:
      t[i,j] = d[j]
      p[i] -= d[j]
      d[j] = 0
      C[i,j] = np.inf
  c = np.sum(cost*t)
  return t, c

In [ ]:
def BARQUILLA_2(cost, dem, prod, trans):
  C = np.array(tuple(cost))
  d = list(dem)
  p = list(prod)
  t = np.array(tuple(trans))

  while True:
    li = []
    lj = []
    lc = []

    zi, zj = np.nonzero(t == 0)
    ni, nj = np.nonzero(t)
    n = len(zi)
    moda = mode(nj)

    for k in range(n):
      i = [zi[k], zi[k], int(not zi[k]), int(not zi[k])]
      j = [zj[k], moda, moda, zj[k]]
      c = sum(C[i,j][::2]) - sum(C[i,j][1::2])
      if c < 0:
        li.append(i)
        lj.append(j)
        lc.append(c)
    if len(li) > 0:
      k = np.argmin(lc)
      T = t[li[k],lj[k]]
      c = min(T[1::2])
      T[1::2] -= c
      T[::2] += c
      t[li[k],lj[k]] = T
    else:
      break
  c = np.sum(cost*t)
  return t, c

In [ ]:
base = np.array([[4, 3, 2, 2] , [2, 5, 4, 3], [3, 6, 5, 4], [5, 3, 4, 3]])
que = base[:,0]
pac = base[:,1]
tol = base[:,2]
cua = base[:,3]

prod = [10, 15]
dem = [9,7,5,4]

print(que, pac, tol, cua)



[4 2 3 5] [3 5 6 3] [2 4 5 4] [2 3 4 3]


In [ ]:
costos = np.append([que], [pac], 0)


# print(costos)
#costos = np.array([[0.84,1.03], [0.63,0.17], [1.17,1.09], [3.02,1.84], [3.40,2.61], [3.6,2.65]])
# dem = [4,5,2,2,4,3]
#prod = [15, 10]

m,l = np.shape(costos)

if m == len(dem):
  costos = np.transpose(costos)

if sum(dem) < sum(prod):
  dem.insert(0, sum(prod) - sum(dem))
  costos = np.append(np.zeros((l,1)), costos, 1)
elif sum(prod) < sum(dem):
  print('Error, no puede haber más demanda que producción')

suma = sum(prod)
print(f'{costos}\n{dem}\n{prod}')
dem = tuple(dem)
prod = tuple(prod)

print(MEN(costos,dem,prod))
# print(MCM(costos,dem,prod))
# print(MAV(costos,dem,prod))

print('\n\n')

t, c = MEN(costos, dem, prod)
tpa, cpa = BARQUILLA_2(costos, dem, prod, t)
print(tpa)
print(cpa)

[[4 2 3 5]
 [3 5 6 3]]
[9, 7, 5, 4]
[10, 15]
(array([[9, 1, 0, 0],
       [0, 6, 5, 4]]), 110)



[[0 7 3 0]
 [9 0 2 4]]
74


In [ ]:
costos = np.append([que], [tol], 0)


# print(costos)
#costos = np.array([[0.84,1.03], [0.63,0.17], [1.17,1.09], [3.02,1.84], [3.40,2.61], [3.6,2.65]])
# dem = [4,5,2,2,4,3]
#prod = [15, 10]

m,l = np.shape(costos)

if m == len(dem):
  costos = np.transpose(costos)

if sum(dem) < sum(prod):
  dem.insert(0, sum(prod) - sum(dem))
  costos = np.append(np.zeros((l,1)), costos, 1)
elif sum(prod) < sum(dem):
  print('Error, no puede haber más demanda que producción')

suma = sum(prod)
print(f'{costos}\n{dem}\n{prod}')
dem = tuple(dem)
prod = tuple(prod)

print(MEN(costos,dem,prod))
# print(MCM(costos,dem,prod))
# print(MAV(costos,dem,prod))

print('\n\n')

t, c = MEN(costos, dem, prod)
tto, cto = BARQUILLA_2(costos, dem, prod, t)
print(tto)
print(cto)

[[4 2 3 5]
 [2 4 5 4]]
(9, 7, 5, 4)
(10, 15)
(array([[9, 1, 0, 0],
       [0, 6, 5, 4]]), 103)



[[0 7 3 0]
 [9 0 2 4]]
67


In [ ]:
costos = np.append([que], [cua], 0)


# print(costos)
#costos = np.array([[0.84,1.03], [0.63,0.17], [1.17,1.09], [3.02,1.84], [3.40,2.61], [3.6,2.65]])
# dem = [4,5,2,2,4,3]
#prod = [15, 10]

m,l = np.shape(costos)

if m == len(dem):
  costos = np.transpose(costos)

if sum(dem) < sum(prod):
  dem.insert(0, sum(prod) - sum(dem))
  costos = np.append(np.zeros((l,1)), costos, 1)
elif sum(prod) < sum(dem):
  print('Error, no puede haber más demanda que producción')

suma = sum(prod)
print(f'{costos}\n{dem}\n{prod}')
dem = tuple(dem)
prod = tuple(prod)

print(MEN(costos,dem,prod))
# print(MCM(costos,dem,prod))
# print(MAV(costos,dem,prod))

print('\n\n')

t, c = MEN(costos, dem, prod)
tcu, ccu = BARQUILLA_2(costos, dem, prod, t)
print(tcu)
print(ccu)

[[4 2 3 5]
 [2 3 4 3]]
(9, 7, 5, 4)
(10, 15)
(array([[9, 1, 0, 0],
       [0, 6, 5, 4]]), 88)



[[0 7 3 0]
 [9 0 2 4]]
61


In [ ]:
print(f'los costos de pordución de pachuca son: {5} + {5.5*1.5} = {5 + 5.5*1.5} millones')
print(f'Los resultados de el metodo de transporte en pachuca son costos = {cpa/10} millones\n{tpa}\n')
ca = 5 + 5.5*1.5 + cpa/10

print(f'los costos de pordución de toluca son: {5} + {4.5*1.5} = {5 + 4.5*1.5} millones')
print(f'Los resultados de el metodo de transporte en toluca son costos = {cto/10} millones\n{tto}\n')
cb = 5 + 4.5*1.5 + cto/10

print(f'los costos de pordución de cuautal son: {5} + {6*1.5} = {5 + 6*1.5} millones')
print(f'Los resultados de el metodo de transporte en cuautla son costos = {ccu/10} millones\n{tcu}\n')
cc = 5 + 6*1.5 + ccu/10

sol3 = f'Los costos totales de construir en Pachuca son {ca}\nLos costos totales de construir en Toluca son {cb}\nLos costos totales de construir en Cuautla son {cc}\nPor lo tanto se decide construir en Toluca'
print(sol3)

los costos de pordución de pachuca son: 5 + 8.25 = 13.25 millones
Los resultados de el metodo de transporte en pachuca son costos = 7.4 millones
[[0 7 3 0]
 [9 0 2 4]]

los costos de pordución de toluca son: 5 + 6.75 = 11.75 millones
Los resultados de el metodo de transporte en toluca son costos = 6.7 millones
[[0 7 3 0]
 [9 0 2 4]]

los costos de pordución de cuautal son: 5 + 9.0 = 14.0 millones
Los resultados de el metodo de transporte en cuautla son costos = 6.1 millones
[[0 7 3 0]
 [9 0 2 4]]

Los costos totales de construir en Pachuca son 20.65
Los costos totales de construir en Toluca son 18.45
Los costos totales de construir en Cuautla son 20.1
Por lo tanto se decide construir en Toluca


##MAquinas Producción

In [ ]:
t = 60/(4 + 25)
cap =1860
j = t * 8
nm100 = cap / j
print(np.ceil(nm100))

t90 = 0.9 * t
j90 = t90 * 8
nm90 = cap / j90
print(nm90, np.ceil(nm90))

sol1 = f'La cantidad de máqunas que se deben comprar para na tasa de utilización de 100% es {np.ceil(nm100)}\nLa cantidad de máqunas que se deben comprar para na tasa de utilización de 90% es {np.ceil(nm90)}\n'
print(sol1)

113.0
124.8611111111111 125.0
La cantidad de máqunas que se deben comprar para na tasa de utilización de 100% es 113.0
La cantidad de máqunas que se deben comprar para na tasa de utilización de 90% es 125.0



##División de Salas

In [ ]:
arreglo = 250000#
asientos_actual = 600
asientoa_nuevo = 200
e_clientes = 100#

dia = 2
semana = dia*3
año = 52 * semana #
boleto = 300#

costo_actual = e_clientes * año * boleto
print(costo_actual)

#Si se hace la división de salas

costo_nuevo = -arreglo + e_clientes * 2 * año * boleto
print(costo_nuevo)

sol2 = f'Analizando los dos casos:\nActual:\n\tBeneficios anuales = {costo_actual}\n\nAl dividir la sala\n\tBeneficios anuales = {costo_nuevo}\n\nPor lo tanto, se recomienda hacer la división de la sala.'
print(sol2)


9360000
18470000
Analizando los dos casos:
Actual:
	Beneficios anuales = 9360000

Al dividir la sala
	Beneficios anuales = 18470000

Por lo tanto, se recomienda hacer la división de la sala.


##Resultados

In [ ]:
texto = open("Solución Examen 1.txt", "w")

texto.write('3.-Transporte\n')

texto.write(sol3)

texto.write('\n\n\n1.-Cantidad de máquinas de producción\n')

texto.write(sol1)

texto.write('\n\n2.-Sala de cine\n')

texto.write(sol2)

texto.close()

# np.savetxt('datos.txt', ayuda,'%10.0f')