<a href="https://colab.research.google.com/github/Vixuz144/Admin-Prod/blob/main/Simulaci%C3%B3n_de_Dise%C3%B1o_de_Experimentos_Bebidas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from random import random, seed
import numpy as np
import pandas as pd

In [2]:
def sim(b):
  n = len(b)-1
  m = n**2-1
  M = np.ones((m,n+1))
  for i in range(n):
    l = []
    for j in range(m):
      t = f'{j%2}'*2**i
      for q in t:
        l.append(int(bool(int(q))))
    M[:,i+1] = l[:m]
  M=2*np.array(M)-1
  print(M)

  l = []
  for i in M:
    print(i*b)
    print(sum(i*b))
    l.append(np.dot(i,b))

  return l

In [5]:
s = sim([17.6403125, -6.279375, -3.1931249999999975, -2.9825000000000017])
print(s)
t = pd.DataFrame(s)
t.to_excel('Res_exp.xlsx')

[[ 1. -1. -1. -1.]
 [ 1.  1. -1. -1.]
 [ 1. -1.  1. -1.]
 [ 1.  1.  1. -1.]
 [ 1. -1. -1.  1.]
 [ 1.  1. -1.  1.]
 [ 1. -1.  1.  1.]
 [ 1.  1.  1.  1.]]
[17.6403125  6.279375   3.193125   2.9825   ]
30.095312500000002
[17.6403125 -6.279375   3.193125   2.9825   ]
17.5365625
[17.6403125  6.279375  -3.193125   2.9825   ]
23.709062500000005
[17.6403125 -6.279375  -3.193125   2.9825   ]
11.150312500000005
[17.6403125  6.279375   3.193125  -2.9825   ]
24.1303125
[17.6403125 -6.279375   3.193125  -2.9825   ]
11.571562499999995
[17.6403125  6.279375  -3.193125  -2.9825   ]
17.744062500000002
[17.6403125 -6.279375  -3.193125  -2.9825   ]
5.185312500000002
[30.095312500000002, 17.5365625, 23.709062500000005, 11.150312500000005, 24.1303125, 11.571562499999995, 17.744062500000002, 5.185312500000002]
