<a href="https://colab.research.google.com/github/Vixuz144/Admin-Prod/blob/main/Simulador_de_Experimentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [175]:
from random import random, seed, gauss
import numpy as np
import pandas as pd

In [176]:
def modelo(x, y, nr, a, b, s, dec):
  seed(s)
  n = len(x)
  e = 2**n
  m1 = np.zeros((e,n))
  for i in range(n):
    l = []
    for j in range(e):
      t = f'{j%2}'*2**i
      for q in t:
        l.append(int( bool(int(q))))
    m1[:,i] = l[:e]
  print(m1)

  rep = []
  for _ in range(nr):
    l = []
    for i in m1:
      r = []
      for k in range(n):
        r.append(gauss(x[k],y[k]))
      l.append(a+(b-a)*random()+np.dot(r,i))
    rep.append(np.round(l,dec))
  return np.transpose(rep)

In [179]:
m = [-10,18,14,20]
s = [0.3,1,0.5,2]
l = modelo(m, s, 4, a=10, b=12, s=314, dec=2)
print(l)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 1. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 1. 0. 1.]
 [0. 0. 1. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10.47 10.41 11.76 11.38]
 [ 0.46  1.63  1.75  1.44]
 [28.98 28.44 27.75 30.68]
 [20.1  20.44 18.42 19.29]
 [24.28 24.74 24.56 24.91]
 [14.48 15.89 14.58 15.68]
 [42.87 39.25 43.1  40.63]
 [31.6  29.1  34.27 33.38]
 [33.9  32.17 29.51 32.36]
 [21.33 19.6  18.49 23.34]
 [48.64 50.4  52.77 54.35]
 [39.94 37.66 37.08 40.69]
 [46.07 45.94 45.81 43.75]
 [40.08 32.14 33.9  37.02]
 [65.12 64.45 56.63 66.79]
 [54.58 55.35 55.99 52.49]]


In [180]:
t = pd.DataFrame(l)
print(t)
t.to_excel('Primer_exp.xlsx')

        0      1      2      3
0   10.47  10.41  11.76  11.38
1    0.46   1.63   1.75   1.44
2   28.98  28.44  27.75  30.68
3   20.10  20.44  18.42  19.29
4   24.28  24.74  24.56  24.91
5   14.48  15.89  14.58  15.68
6   42.87  39.25  43.10  40.63
7   31.60  29.10  34.27  33.38
8   33.90  32.17  29.51  32.36
9   21.33  19.60  18.49  23.34
10  48.64  50.40  52.77  54.35
11  39.94  37.66  37.08  40.69
12  46.07  45.94  45.81  43.75
13  40.08  32.14  33.90  37.02
14  65.12  64.45  56.63  66.79
15  54.58  55.35  55.99  52.49
